### ISSUE TITLE
The caption is not visible

### ISSUE THREAD

**Issue by bekanntmacher** [contao/contao-demo#48]
<img width="1662" alt="Media_elements_-_Contao_Official_Demo" src="https://github.com/user-attachments/assets/fe66db6d-97fc-41af-b04c-113b77b5aaea">

**Comment by zoglo** [comment]
Maybe something like this:

```css
.content-youtube figure.aspect figcaption,
.content-vimeo figure.aspect figcaption {
    position: absolute;
    /* Because the iframe itself has a border of 2px */
    bottom: 2px; 
    left: 2px;
    right: 2px;
    
    background: linear-gradient(to top, rgba(0, 0, 0, .7), transparent);
    color: #fff:

    padding: 2px;

    text-align: center;

    /* Same z-index as the iframe */
    z-index: 5;
}
```

![image](https://github.com/user-attachments/assets/bba9ebbe-99e9-4d3f-86c1-e57ce4e0f1a5)
